# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  install:
    aliases:
      - default
    cmds:
      - go install github.com/evilmartians/lefthook@latest && lefthook install
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    desc: install deps
    preconditions:
      - which go

  clean:
    cmds:
      - lefthook uninstall && rm -f $(go env GOPATH)/bin/lefthook
      - rm -f $(go env GOPATH)/bin/golangci-lint
      - go clean -modcache
    desc: clean deps
    preconditions:
      - which go

  # lint
  lint:
    cmds:
      - golangci-lint run {{ .OPTIONS }} ${TARGETS}
    desc: lint
    env:
      TARGETS: ./...
    preconditions:
      - which golangci-lint

  format:
    cmds:
      - task: lint
        vars:
          OPTIONS: --fix
    desc: format

  # test
  test:
    cmds:
      - go test ./internal/... {{ .OPTIONS }}
    desc: run tests
    preconditions:
      - which go

  test:verbose:
    cmds:
      - task: test
        vars:
          OPTIONS: -v
    desc: run tests (verbose)

  # coverage
  coverage:
    cmds:
      - task: test
        vars:
          OPTIONS: -cover
    desc: run tests with coverage report

  coverage:verbose:
    cmds:
      - task: test
        vars:
          OPTIONS: -cover -v
    desc: run tests with coverage report (verbose)
